### ISSUE TITLE
Update AFrame & THREE usage

### ISSUE THREAD

**Issue by DougReeder** [DougReeder/aframe-shader-buildings#10]
* rework using BufferGeomery instead of Geometry
* Update A-Frame to latest in example

**Comment by kylebakerio** [comment]
Hope this update happens! Just came here to use this component, was sad to see it wasn't available. 

How big are the changes needed?

**Comment by DougReeder** [comment]
It's straightforward to replace Geometry with BufferGeometry, but there's more than a little fiddly detail.

**Comment by DougReeder** [comment]
Fixed in v1.0.0
